apiVersion: 1

datasources:
  - name: Sharelife-Prometheus
    uid: sharelife-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
