#!/usr/bin/env python3
"""Interactive init wizard for Sharelife runtime config generation."""

from __future__ import annotations

import argparse
from pathlib import Path


PROVIDER_CHOICES = ("openai", "claude", "deepseek")
PRESET_CHOICES = (
    ("standard_qa", "community/basic"),
    ("sharelife_companion", "community/support-care"),
    ("research_safe", "community/research-safe"),
)


def _to_bool(value: str | bool | None, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    text = str(value or "").strip().lower()
    if not text:
        return default
    if text in {"1", "true", "yes", "on", "y"}:
        return True
    if text in {"0", "false", "no", "off", "n"}:
        return False
    return default


def _ask_text(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _ask_bool(prompt: str, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    text = input(f"{prompt} ({hint}): ").strip()
    return _to_bool(text, default=default)


def _ask_choice(prompt: str, choices: tuple[str, ...], default: str) -> str:
    print(prompt)
    for index, item in enumerate(choices, start=1):
        marker = " (default)" if item == default else ""
        print(f"  {index}. {item}{marker}")
    text = input("Select by number: ").strip()
    if not text:
        return default
    try:
        index = int(text)
    except Exception:
        return default
    if 1 <= index <= len(choices):
        return choices[index - 1]
    return default


def _ask_preset(default: str = "standard_qa") -> str:
    names = tuple(item[0] for item in PRESET_CHOICES)
    print("Choose a starter preset:")
    for index, item in enumerate(PRESET_CHOICES, start=1):
        marker = " (default)" if item[0] == default else ""
        print(f"  {index}. {item[0]} -> {item[1]}{marker}")
    text = input("Select by number: ").strip()
    if not text:
        return default
    try:
        index = int(text)
    except Exception:
        return default
    if 1 <= index <= len(names):
        return names[index - 1]
    return default


def _preset_template_id(preset: str) -> str:
    for name, template_id in PRESET_CHOICES:
        if name == preset:
            return template_id
    return "community/basic"


def build_yaml(
    *,
    provider: str,
    api_key: str,
    preset: str,
    webui_auth_enabled: bool,
    member_password: str,
    admin_password: str,
    enable_plugin_install_exec: bool,
) -> str:
    selected_provider = provider if provider in PROVIDER_CHOICES else "openai"
    preset_template = _preset_template_id(preset)
    auth_member = member_password if webui_auth_enabled else ""
    auth_admin = admin_password if webui_auth_enabled else ""

    return (
        "# Generated by scripts/sharelife_init_wizard.py\n"
        f"provider: \"{selected_provider}\"\n\n"
        "providers:\n"
        "  openai:\n"
        f"    api_key: \"{api_key if selected_provider == 'openai' else ''}\"\n"
        "    base_url: \"https://api.openai.com/v1\"\n"
        "    model: \"gpt-5-mini\"\n"
        "  claude:\n"
        f"    api_key: \"{api_key if selected_provider == 'claude' else ''}\"\n"
        "    base_url: \"\"\n"
        "    model: \"\"\n"
        "  deepseek:\n"
        f"    api_key: \"{api_key if selected_provider == 'deepseek' else ''}\"\n"
        "    base_url: \"\"\n"
        "    model: \"\"\n\n"
        "sharelife:\n"
        f"  startup_template_id: \"{preset_template}\"\n"
        "  webui:\n"
        "    enabled: true\n"
        "    host: \"127.0.0.1\"\n"
        "    port: 8106\n"
        "    auth:\n"
        f"      member_password: \"{auth_member}\"\n"
        f"      admin_password: \"{auth_admin}\"\n"
        "      token_ttl_seconds: 7200\n"
        "      allow_query_token: false\n"
        "      login_rate_limit_window_seconds: 60\n"
        "      login_rate_limit_max_attempts: 10\n"
        "  profile_pack:\n"
        "    signing_key_id: \"default\"\n"
        "    signing_secret: \"\"\n"
        "    trusted_signing_keys: {}\n"
        "    secrets_encryption_key: \"\"\n"
        "    plugin_install:\n"
        f"      enabled: {'true' if enable_plugin_install_exec else 'false'}\n"
        "      command_timeout_seconds: 180\n"
        "      allowed_command_prefixes: \"astrbot,pip,uv,npm,pnpm\"\n"
        "      allow_http_source: false\n"
        "      require_success_before_apply: false\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a Sharelife runtime config with guided defaults.")
    parser.add_argument("--output", default="config.generated.yaml", help="output config path")
    parser.add_argument("--provider", choices=PROVIDER_CHOICES, default="")
    parser.add_argument("--api-key", default="")
    parser.add_argument("--preset", choices=tuple(item[0] for item in PRESET_CHOICES), default="")
    parser.add_argument("--webui-auth", default="", help="true/false")
    parser.add_argument("--member-password", default="")
    parser.add_argument("--admin-password", default="")
    parser.add_argument("--enable-plugin-install-exec", default="", help="true/false")
    parser.add_argument("--yes", action="store_true", help="non-interactive mode with defaults")
    parser.add_argument("--print-only", action="store_true", help="print generated yaml to stdout only")
    return parser.parse_args()


def run() -> int:
    args = parse_args()
    non_interactive = bool(args.yes)

    if non_interactive:
        provider = str(args.provider or "openai")
        api_key = str(args.api_key or "")
        preset = str(args.preset or "standard_qa")
        webui_auth_enabled = _to_bool(args.webui_auth, default=False)
        member_password = str(args.member_password or "")
        admin_password = str(args.admin_password or "")
        enable_plugin_install_exec = _to_bool(args.enable_plugin_install_exec, default=False)
    else:
        print("Sharelife Init Wizard")
        print("This wizard generates a runnable baseline config for AstrBot + Sharelife.")
        provider = _ask_choice(
            "Choose model provider:",
            PROVIDER_CHOICES,
            default=str(args.provider or "openai"),
        )
        api_key = _ask_text("Input provider API key (leave empty for later)", default=str(args.api_key or ""))
        preset = _ask_preset(default=str(args.preset or "standard_qa"))
        webui_auth_enabled = _ask_bool(
            "Enable WebUI member/admin password auth now?",
            default=_to_bool(args.webui_auth, default=False),
        )
        member_password = ""
        admin_password = ""
        if webui_auth_enabled:
            member_password = _ask_text("Member password", default=str(args.member_password or ""))
            admin_password = _ask_text("Admin password", default=str(args.admin_password or ""))
        enable_plugin_install_exec = _ask_bool(
            "Enable plugin install command execution? (recommended: no for first run)",
            default=_to_bool(args.enable_plugin_install_exec, default=False),
        )

    yaml_text = build_yaml(
        provider=provider,
        api_key=api_key,
        preset=preset,
        webui_auth_enabled=webui_auth_enabled,
        member_password=member_password,
        admin_password=admin_password,
        enable_plugin_install_exec=enable_plugin_install_exec,
    )

    if args.print_only:
        print(yaml_text)
        return 0

    output_path = Path(args.output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(yaml_text, encoding="utf-8")
    print(f"config generated: {output_path}")
    print("next steps:")
    print("  1) load this config into your AstrBot runtime")
    print("  2) run /sharelife_pref and /sharelife_market in chat")
    print("  3) check QUICKSTART.md for the 3-minute verification loop")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
